<?php

namespace Tests\Functional;

use Faker\Generator;
use Naweown\Item;
use Naweown\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ItemControllerTest extends TestCase
{

    use DatabaseMigrations;


    public function testPageIsUpAndRunning()
    {
        $this->get('items');
        $this->assertResponseOk();
    }

    public function testItemsCanOnlyBeAddedByUsersWithAnActivatedAccount()
    {
        $this->be($this->modelFactoryFor(User::class));

        $this->post('items', $this->getValidData());

        $this->assertResponseStatus(403); //access forbidden
    }

    public function getValidData()
    {
        $validData = [
            'title' => "Some cool title",
            'description' => "THe return of the Jedi",
            'slug' => 'oops-oops'
        ];

        return $validData;
    }

    public function testSlugIsAutoGeneratedIfItWasProvided()
    {

        $user = $this->modelFactoryFor(User::class);
        $user->activateAccount();

        $this->be($user);

        $validData = $this->getValidData();

        array_pop($validData); //remove the 'slug'index from the array

        $expectedSlug = str_slug($validData['title']);

        $this->post('items', $validData);

        $this->assertRedirectedTo('items/1');
        $this->seeInDatabase('items', ['slug' => $expectedSlug]);
    }

    public function testSlugIsNotGeneratedIfOneIsProvided()
    {
        $user = $this->modelFactoryFor(User::class);
        $user->activateAccount();

        $this->be($user);

        $validData = $this->getValidData();

        $this->post('items', $validData);

        $this->assertRedirectedTo('items/1');
        $this->seeInDatabase('items', ['slug' => array_pop($validData)]);
    }

    public function testItemCanOnlyBeModifiedByItsCreator()
    {
        //Modification here refers to deletions and updates
        
        /**
         * TODO : Write this
         * In the `save` method of models, the model is returned which then leads to it's attribute casting.
         * So whenever i do $item->save(), the world drops because Sqlite doesn't have a native json table.
         * PROBABLE FIXES => Override DBAL's "DATA TYPES" for the sqlite platform
         *                   Switch to MYSQL for tests (fuck this slow tests anyways!!!)
         */

        $this->markTestSkipped();
    }

    public function testItemCanBeUpdated()
    {
        //Take a look at the previous test
        $this->markTestSkipped();
    }
}
